const router = require("express").Router();
const { protect, requireRole } = require("../middleware/authMiddleware");
const controller = require("../controllers/boardMemberController");
const manage = requireRole("president", "vice-president");
router.get("/", controller.getBoardMembers);
router.get("/:id", controller.getById);
router.post("/", protect, manage, controller.createBoardMember);
router.put("/:id", protect, manage, controller.updateBoardMember);
router.delete("/:id", protect, manage, controller.deleteBoardMember);
module.exports = router;
