const router = require('express').Router();
const { protect } = require('../middleware/authMiddleware');
const member = require('../middleware/communityAuth');
const controller = require('../controllers/communityController');
router.use((req, res, next) => { res.set('Cache-Control', 'no-store'); next(); });
router.get('/session/config', member.configuration);
router.get('/session/nonce', member.challenge);
router.post('/session/google', member.login);
router.get('/mine', member.requireMember, controller.mine);
router.get('/admin', protect, controller.adminList);
router.patch('/:id/status', protect, controller.moderate);
router.get('/', controller.list);
router.post('/', member.optionalMember, controller.create);
router.post('/:id/manage', member.optionalMember, controller.owner);
router.post('/:id/close', member.optionalMember, controller.owner);
router.post('/:id/edit', member.optionalMember, controller.owner);
router.post('/:id/delete', member.optionalMember, controller.owner);
router.post('/:id/claim', member.requireMember, controller.owner);
module.exports = router;
