const router = require("express").Router();
const { protect, requireRole } = require("../middleware/authMiddleware");
const controller = require("../controllers/galleryController");
const manage = requireRole("president", "vice-president", "social-media-manager", "creative-director", "it-director");
router.get("/", controller.getAlbums);
router.get("/:id", controller.getById);
router.post("/", protect, manage, controller.createAlbum);
router.put("/:id", protect, manage, controller.updateAlbum);
router.delete("/:id", protect, manage, controller.deleteAlbum);
module.exports = router;
